name: Hexo Deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Setup Hexo
        run: |
          npm install hexo-cli -g
          npm install

      - name: Deploy
        run: |
          cd docs
          hexo clean
          hexo generate
          hexo deploy